import { Font, renderToBuffer } from '@react-pdf/renderer'
import { ExpenseReportTemplate } from './expense-report-template'
import { ALEF_FONT_BASE64 } from './font-data'
import { signPdfBuffer } from './sign-pdf'

let isFontRegistered = false

function registerFont() {
    if (isFontRegistered) return
    try {
        Font.register({
            family: 'Alef',
            src: `data:font/ttf;base64,${ALEF_FONT_BASE64}`
        })
        isFontRegistered = true
    } catch (error) {
        console.error('Failed to register PDF font:', error)
    }
}

export async function generateExpenseReportPDFBuffer(data: { 
    expenses: any[], 
    manualRefunds?: any[],
    month: string, 
    year: string, 
    businessName: string, 
    totalAmount: number 
}): Promise<Buffer> {
    registerFont()
    const unsignedBuffer = await renderToBuffer(<ExpenseReportTemplate {...data} />)
    return await signPdfBuffer(unsignedBuffer, {
        signerName: data.businessName || 'Kesefly',
        reason: 'Expense report generated by Kesefly',
    })
}
