// Note: This file requires @react-pdf/renderer to be installed
// Run: npm install @react-pdf/renderer

import { Font, renderToBuffer } from '@react-pdf/renderer'
import { InvoiceTemplate } from './invoice-template'
import { prisma } from '@/lib/db'
import { signPdfBuffer } from './sign-pdf'

import { ALEF_FONT_BASE64 } from './font-data'

// Keep track of font registration state
let isFontRegistered = false

function registerFont() {
    if (isFontRegistered) return

    try {
        Font.register({
            family: 'Alef',
            src: `data:font/ttf;base64,${ALEF_FONT_BASE64}`
        })
        isFontRegistered = true
    } catch (error) {
        console.error('Failed to register PDF font:', error)
    }
}

interface GenerateCreditNotePDFParams {
    creditNoteId: string
    userId: string
}

export async function generateCreditNotePDF({ creditNoteId, userId }: GenerateCreditNotePDFParams): Promise<{ buffer: Buffer, filename: string }> {
    try {
        registerFont()

        const creditNote = await prisma.creditNote.findFirst({
            where: {
                id: creditNoteId,
                userId: userId
            },
            include: {
                invoice: {
                    include: {
                        client: true
                    }
                },
                user: {
                    include: {
                        businessProfile: true,
                        budgets: {
                            where: { type: 'BUSINESS' },
                            take: 1
                        }
                    }
                }
            }
        })

        if (!creditNote) {
            throw new Error('Credit Note not found')
        }

        const businessProfile = creditNote.user.businessProfile
        const businessBudget = creditNote.user.budgets[0]

        // Prepare data
        const creditNoteData = {
            title: 'חשבונית זיכוי',
            documentNumberLabel: 'מספר זיכוי',
            invoiceNumber: creditNote.creditNoteNumber,
            issueDate: creditNote.issueDate.toISOString(),
            dueDate: creditNote.issueDate.toISOString(),
            status: 'זיכוי',
            
            businessName: businessProfile?.companyName || 'החברה שלי',
            businessId: businessProfile?.companyId || undefined,
            businessAddress: businessProfile?.address || undefined,
            businessPhone: businessProfile?.phone || undefined,
            businessEmail: businessProfile?.email || undefined,
            businessLogo: businessProfile?.logoUrl || undefined,
            businessSignature: businessProfile?.signatureUrl || undefined,
            
            clientName: creditNote.invoice.client?.name || 'N/A',
            clientId: creditNote.invoice.client?.taxId || undefined,
            
            subtotal: creditNote.creditAmount,
            vatRate: (creditNote.vatAmount / creditNote.creditAmount) * 100,
            vatAmount: creditNote.vatAmount,
            total: creditNote.totalCredit,
            currency: 'ILS',
            
            notes: creditNote.reason ? `בגין חשבונית ${creditNote.invoice.invoiceNumber}: ${creditNote.reason}` : `בגין חשבונית ${creditNote.invoice.invoiceNumber}`
        }

        const unsignedBuffer = await renderToBuffer(<InvoiceTemplate data={creditNoteData} />)
        const buffer = await signPdfBuffer(unsignedBuffer, {
            signerName: creditNoteData.businessName || 'Kesefly',
            reason: 'Original credit note generated by Kesefly',
        })

        const safeBusinessName = (creditNoteData.businessName || 'Business').replace(/[^a-zA-Z0-9\u0590-\u05FF\s_-]/g, '')
        const filename = `${creditNoteData.invoiceNumber} Credit Note from ${safeBusinessName}.pdf`

        return { buffer, filename }
    } catch (error) {
        console.error('generateCreditNotePDF error:', error)
        throw error
    }
}
