/**
 * PDF Digital Signature Utility
 */

export interface SignPdfOptions {
    signerName?: string
    reason?: string
    location?: string
    contactInfo?: string
}

export async function signPdfBuffer(
    pdfBuffer: Buffer,
    options: SignPdfOptions = {}
): Promise<Buffer> {
    const p12Base64 = process.env.PDF_SIGNING_P12_BASE64
    const p12Password = process.env.PDF_SIGNING_P12_PASSWORD

    console.log('[signPdfBuffer] Starting signature process...')

    try {
        const { SignPdf } = await import('@signpdf/signpdf')
        const { P12Signer } = await import('@signpdf/signer-p12')
        const { pdflibAddPlaceholder } = await import('@signpdf/placeholder-pdf-lib')
        const { PDFDocument, rgb, StandardFonts } = await import('pdf-lib')

        const {
            signerName = 'Kesefly',
            reason = 'Digitally signed document generated by Kesefly',
            location = 'Israel',
            contactInfo = 'support@kesefly.co.il',
        } = options

        const pdfDoc = await PDFDocument.load(pdfBuffer, { 
            ignoreEncryption: true,
            updateMetadata: false 
        })
        
        // 1. Add Visible Stamp
        await addVisibleStamp(pdfDoc, signerName, { rgb, StandardFonts })

        // 2. If no cert, return the PDF with the visual stamp only
        if (!p12Base64 || !p12Password) {
            console.warn('[signPdfBuffer] Missing environment variables. Returning PDF with visual stamp only.')
            const visualOnlyPdf = await pdfDoc.save()
            return Buffer.from(visualOnlyPdf)
        }

        // 3. Add cryptographic signature
        pdflibAddPlaceholder({
            pdfDoc,
            reason,
            contactInfo,
            name: signerName,
            location,
            signatureLength: 8192,
            widgetRect: [0, 0, 0, 0],
        })

        const pdfWithPlaceholder = await pdfDoc.save({ useObjectStreams: false })
        const p12Buffer = Buffer.from(p12Base64, 'base64')
        const signer = new P12Signer(p12Buffer, { passphrase: p12Password })
        const signPdf = new SignPdf()
        const signedPdf = await signPdf.sign(Buffer.from(pdfWithPlaceholder), signer)

        console.log('[signPdfBuffer] PDF signed successfully!')
        return Buffer.from(signedPdf)
    } catch (error) {
        console.error('[signPdfBuffer] Failed to sign PDF:', error)
        return pdfBuffer
    }
}

async function addVisibleStamp(pdfDoc: any, signerName: string, { rgb, StandardFonts }: any) {
    const pages = pdfDoc.getPages()
    if (pages.length === 0) return
    const firstPage = pages[0]
    const { width } = firstPage.getSize()

    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

    // Position: Very bottom of the page, below footer
    const stampWidth = 180
    const stampHeight = 44
    const stampX = 20
    const stampY = 15

    const greenColor = rgb(0.063, 0.725, 0.506) 
    const darkGreenColor = rgb(0.039, 0.553, 0.380) 
    const lightGreenBg = rgb(0.941, 0.992, 0.969) 

    firstPage.drawRectangle({
        x: stampX, y: stampY,
        width: stampWidth, height: stampHeight,
        color: lightGreenBg, borderColor: greenColor, borderWidth: 1.5, opacity: 0.9,
    })

    firstPage.drawText('Digitally Signed', {
        x: stampX + 12, y: stampY + stampHeight - 16,
        size: 10, font: helveticaBold, color: darkGreenColor,
    })

    const now = new Date()
    const dateStr = `${String(now.getDate()).padStart(2, '0')}/${String(now.getMonth() + 1).padStart(2, '0')}/${now.getFullYear()} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`

    // Sanitize signer name to ASCII only (Helvetica doesn't support Hebrew)
    const asciiName = signerName.replace(/[^\x20-\x7E]/g, '').trim() || 'Kesefly'

    firstPage.drawText(`By: ${asciiName}`, {
        x: stampX + 12, y: stampY + 16, size: 8, font: helvetica, color: rgb(0.3, 0.3, 0.3),
    })
    firstPage.drawText(`Date: ${dateStr}`, {
        x: stampX + 12, y: stampY + 6, size: 7, font: helvetica, color: rgb(0.5, 0.5, 0.5),
    })
}
