/**
 * PDF Digital Signature Utility
 * 
 * Signs PDF buffers with a PKCS#7 (CMS) digital signature using a P12 certificate.
 * Also adds a visible "Digitally Signed" stamp on the first page.
 */

export interface SignPdfOptions {
    signerName?: string       // Name shown in the signature (default: "Kesefly")
    reason?: string           // Reason for signing
    location?: string         // Location (default: "Israel")
    contactInfo?: string      // Contact email
}

/**
 * Signs a PDF buffer with a digital signature and adds a visible stamp.
 */
export async function signPdfBuffer(
    pdfBuffer: Buffer,
    options: SignPdfOptions = {}
): Promise<Buffer> {
    const p12Base64 = process.env.PDF_SIGNING_P12_BASE64
    const p12Password = process.env.PDF_SIGNING_P12_PASSWORD

    console.log('[signPdfBuffer] Starting signature process...')
    console.log('[signPdfBuffer] Env check - Base64 defined:', !!p12Base64, 'Password defined:', !!p12Password)
    
    // Graceful fallback: no certificate configured → return unsigned
    if (!p12Base64 || !p12Password) {
        console.warn('[signPdfBuffer] Missing environment variables. SIGNATURE SKIPPED.')
        return pdfBuffer
    }

    try {
        // Dynamic imports to avoid ERR_REQUIRE_ESM issues in Next.js/Vercel
        const { SignPdf } = await import('@signpdf/signpdf')
        const { P12Signer } = await import('@signpdf/signer-p12')
        const { pdflibAddPlaceholder } = await import('@signpdf/placeholder-pdf-lib')
        const { PDFDocument, rgb, StandardFonts } = await import('pdf-lib')

        const p12Buffer = Buffer.from(p12Base64, 'base64')
        const {
            signerName = 'Kesefly',
            reason = 'Digitally signed document generated by Kesefly',
            location = 'Israel',
            contactInfo = 'support@kesefly.co.il',
        } = options

        // Step 1: Load the PDF with pdf-lib and add a visible stamp
        const pdfDoc = await PDFDocument.load(pdfBuffer, { 
            ignoreEncryption: true,
            updateMetadata: false 
        })
        
        // Draw visible signature stamp on the first page
        await addVisibleStamp(pdfDoc, signerName, { rgb, StandardFonts })

        // Step 2: Add signature placeholder using pdf-lib integration
        pdflibAddPlaceholder({
            pdfDoc,
            reason,
            contactInfo,
            name: signerName,
            location,
            signatureLength: 8192,
            widgetRect: [0, 0, 0, 0],
        })

        // Step 3: Save the PDF with placeholder
        const pdfWithPlaceholder = await pdfDoc.save({ useObjectStreams: false })

        // Step 4: Sign with P12
        const signer = new P12Signer(p12Buffer, { passphrase: p12Password })
        const signPdf = new SignPdf()
        const signedPdf = await signPdf.sign(Buffer.from(pdfWithPlaceholder), signer)

        console.log('[signPdfBuffer] PDF signed successfully!')
        return Buffer.from(signedPdf)
    } catch (error) {
        console.error('[signPdfBuffer] Failed to sign PDF:', error)
        return pdfBuffer
    }
}

/**
 * Draws a visible "Digitally Signed" stamp on the first page of the PDF.
 */
async function addVisibleStamp(pdfDoc: any, signerName: string, { rgb, StandardFonts }: any) {
    const pages = pdfDoc.getPages()
    if (pages.length === 0) return

    const firstPage = pages[0]
    const { width, height } = firstPage.getSize()

    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

    // Extreme position for testing: TOP RIGHT of the page
    const stampWidth = 180
    const stampHeight = 44
    const stampX = width - stampWidth - 40 
    const stampY = height - stampHeight - 40

    const greenColor = rgb(0.063, 0.725, 0.506) 
    const darkGreenColor = rgb(0.039, 0.553, 0.380) 
    const lightGreenBg = rgb(0.941, 0.992, 0.969) 

    firstPage.drawRectangle({
        x: stampX,
        y: stampY,
        width: stampWidth,
        height: stampHeight,
        color: lightGreenBg,
        borderColor: greenColor,
        borderWidth: 1.5,
        opacity: 0.95,
    })

    firstPage.drawRectangle({
        x: stampX,
        y: stampY,
        width: 4,
        height: stampHeight,
        color: greenColor,
    })

    const now = new Date()
    const dateStr = `${String(now.getDate()).padStart(2, '0')}/${String(now.getMonth() + 1).padStart(2, '0')}/${now.getFullYear()}`
    const timeStr = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`

    firstPage.drawText('Digitally Signed', {
        x: stampX + 24,
        y: stampY + stampHeight - 16,
        size: 10,
        font: helveticaBold,
        color: darkGreenColor,
    })

    firstPage.drawText('\u2713', {
        x: stampX + 10,
        y: stampY + stampHeight - 16,
        size: 12,
        font: helvetica,
        color: greenColor,
    })

    firstPage.drawText(`By: ${signerName}`, {
        x: stampX + 12,
        y: stampY + 14,
        size: 7.5,
        font: helvetica,
        color: rgb(0.373, 0.416, 0.463),
    })

    firstPage.drawText(`${dateStr} ${timeStr}`, {
        x: stampX + 12,
        y: stampY + 4,
        size: 7,
        font: helvetica,
        color: rgb(0.498, 0.549, 0.596),
    })
}
