/**
 * PDF Digital Signature Utility
 * 
 * Signs PDF buffers with a PKCS#7 (CMS) digital signature using a P12 certificate.
 * Also adds a visible "Digitally Signed" stamp on the first page.
 * 
 * Configuration via environment variables:
 *   PDF_SIGNING_P12_BASE64  — Base64-encoded P12 certificate
 *   PDF_SIGNING_P12_PASSWORD — Password for the P12 certificate
 * 
 * If no certificate is configured, returns the buffer unsigned (graceful fallback).
 */

import { SignPdf } from '@signpdf/signpdf'
import { P12Signer } from '@signpdf/signer-p12'
import { pdflibAddPlaceholder } from '@signpdf/placeholder-pdf-lib'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'

export interface SignPdfOptions {
    signerName?: string       // Name shown in the signature (default: "Kesefly")
    reason?: string           // Reason for signing
    location?: string         // Location (default: "Israel")
    contactInfo?: string      // Contact email
}

/**
 * Signs a PDF buffer with a digital signature and adds a visible stamp.
 * 
 * If no P12 certificate is configured (env vars), returns the original buffer unchanged.
 */
export async function signPdfBuffer(
    pdfBuffer: Buffer,
    options: SignPdfOptions = {}
): Promise<Buffer> {
    const p12Base64 = process.env.PDF_SIGNING_P12_BASE64
    const p12Password = process.env.PDF_SIGNING_P12_PASSWORD

    // Graceful fallback: no certificate configured → return unsigned
    if (!p12Base64 || !p12Password) {
        return pdfBuffer
    }

    try {
        const p12Buffer = Buffer.from(p12Base64, 'base64')
        const {
            signerName = 'Kesefly',
            reason = 'Digitally signed document generated by Kesefly',
            location = 'Israel',
            contactInfo = 'support@kesefly.co.il',
        } = options

        // Step 1: Load the PDF with pdf-lib and add a visible stamp
        const pdfDoc = await PDFDocument.load(pdfBuffer, { 
            ignoreEncryption: true,
            updateMetadata: false 
        })
        
        // Draw visible signature stamp on the first page
        await addVisibleStamp(pdfDoc, signerName)

        // Step 2: Add signature placeholder using pdf-lib integration
        pdflibAddPlaceholder({
            pdfDoc,
            reason,
            contactInfo,
            name: signerName,
            location,
            signatureLength: 8192, // Large enough for most P12 signatures
            widgetRect: [0, 0, 0, 0], // Invisible widget (visual stamp is separate)
        })

        // Step 3: Save the PDF with placeholder
        const pdfWithPlaceholder = await pdfDoc.save({ useObjectStreams: false })

        // Step 4: Sign with P12
        const signer = new P12Signer(p12Buffer, { passphrase: p12Password })
        const signPdf = new SignPdf()
        const signedPdf = await signPdf.sign(Buffer.from(pdfWithPlaceholder), signer)

        return signedPdf
    } catch (error) {
        console.error('[signPdfBuffer] Failed to sign PDF:', error)
        // On error, return the original unsigned buffer rather than breaking the flow
        return pdfBuffer
    }
}

/**
 * Draws a visible "Digitally Signed" stamp on the first page of the PDF.
 * Uses standard Helvetica font (no custom font needed).
 */
async function addVisibleStamp(pdfDoc: PDFDocument, signerName: string) {
    const pages = pdfDoc.getPages()
    if (pages.length === 0) return

    const firstPage = pages[0]
    const { width, height } = firstPage.getSize()

    // Load standard fonts
    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica)
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

    // Stamp dimensions and position (bottom-left of page, above footer area)
    const stampWidth = 200
    const stampHeight = 44
    const stampX = 30  // left margin
    const stampY = 62  // just above the footer

    // Colors
    const greenColor = rgb(0.063, 0.725, 0.506) // #10b981
    const darkGreenColor = rgb(0.039, 0.553, 0.380) // #0a8d61
    const whiteColor = rgb(1, 1, 1)
    const lightGreenBg = rgb(0.941, 0.992, 0.969) // #f0fdf8

    // Draw stamp background
    firstPage.drawRectangle({
        x: stampX,
        y: stampY,
        width: stampWidth,
        height: stampHeight,
        color: lightGreenBg,
        borderColor: greenColor,
        borderWidth: 1.5,
        opacity: 0.95,
    })

    // Draw green accent bar on the left
    firstPage.drawRectangle({
        x: stampX,
        y: stampY,
        width: 4,
        height: stampHeight,
        color: greenColor,
    })

    // Format current date
    const now = new Date()
    const dateStr = `${String(now.getDate()).padStart(2, '0')}/${String(now.getMonth() + 1).padStart(2, '0')}/${now.getFullYear()}`
    const timeStr = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`

    // Draw checkmark + "Digitally Signed" title
    const titleY = stampY + stampHeight - 16
    firstPage.drawText('Digitally Signed', {
        x: stampX + 24,
        y: titleY,
        size: 10,
        font: helveticaBold,
        color: darkGreenColor,
    })

    // Checkmark symbol (using Zapf Dingbats or drawing manually)
    firstPage.drawText('\u2713', {
        x: stampX + 10,
        y: titleY,
        size: 12,
        font: helvetica,
        color: greenColor,
    })

    // Draw signer name
    firstPage.drawText(`By: ${signerName}`, {
        x: stampX + 12,
        y: stampY + 14,
        size: 7.5,
        font: helvetica,
        color: rgb(0.373, 0.416, 0.463), // #5f6a76
    })

    // Draw date/time
    firstPage.drawText(`${dateStr} ${timeStr}`, {
        x: stampX + 12,
        y: stampY + 4,
        size: 7,
        font: helvetica,
        color: rgb(0.498, 0.549, 0.596), // #7f8c98
    })
}
